version: "3.7"

x-yarp-head: &yarp-head
  image: icubteamcode/superbuild-icubhead:v2021.08.1-stable_master_sources
  environment:
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - CAMERA_CONF_FILE
    - CAMERA_MANUALLY
  volumes:
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true


services:
  
  yGrabberCameras:
    <<: *yarp-head
    devices: 
      - "/dev/video0:/dev/video0"
    command: sh -c "if [ ${CAMERA_MANUALLY} = false ]; then yarpdev --from camera/${CAMERA_CONF_FILE}; fi;"

  yrobotinterface:
    <<: *yarp-head
    devices: 
      - "/dev/bosch-i2c-imu:/dev/bosch-i2c-imu"
    command: yarprobotinterface










