version: "3.7"

x-yarp-base: &yarp-base
  image: robotology/yarp
  network_mode: bridge

services:
    yarp-server:
      <<: *yarp-base
      deploy:
        restart_policy:
          condition: on-failure
      command: sh -c "yarp where | grep 'is available at ip' > /dev/null ; if [ ! $$? -eq 0 ]; then yarpserver --write; fi"

    listener:
      <<: *yarp-base
      depends_on:
        - yarp-server
      deploy:
        restart_policy:
          condition: on-failure
      command: sh -c "yarp detect --write && yarp read /test_read"

    talker:
      <<: *yarp-base
      depends_on:
        - listener
      deploy:
        restart_policy:
          condition: on-failure
      command: sh -c "yarp detect --write && echo \"Hello world\" | yarp write ... /test_read" && pkill yarp
