name: Creating changes branch

on: 
  push:
    #repository_dispatch:
    #    types: [user_changes]


#            mv -v ./appsAway/user_changes/* ./icub-tech-apps/dist/database/upgrade/
#            mv -v ./appsAway/user_changes/images/* ./icub-tech-apps/dist/express/images/

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps: 
      # checkout code
      - uses: actions/checkout@v2
        with:
          repository: icub-tech-iit/code
          token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
          path: code
          ref: "user_changes_19072021104501"
            
      # we checkout appsAway
      - name: check ls and pwd
        run: |
          ls
          pwd
      - uses: actions/checkout@v2
        with:
          path: appsAway

      - name: copies user_changes to temporary folder
        run: |
            cd code
            mkdir -p ../test/
            mv -v ./icub-tech-apps/dist/express/evaluate/*.* ../test/ 2>/dev/null || :

      - name: Create branch
        run: |
            cd appsAway
            pwd
            git branch "user_changes_19072021104501_test"
            git checkout "user_changes_19072021104501_test"

      - name: copies user_changes folder
        run: |
            pwd
            mkdir -p ./appsAway/user_changes/
            mv -v ./test/* ./appsAway/user_changes/

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "user_changes_19072021104501_test"
          directory: "./appsAway/"

      - name: check ls and pwd
        run: |
          ls
          pwd
          rm -rf appsAway
          rm -rf code
          ls
          pwd

      - uses: actions/checkout@v2
        with:
          ref: "user_changes_19072021104501_test"

      - name: check ls and pwd
        run: |
          ls
          pwd

      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
            pr_title: "Adding user changes into the website."
            pr_body: "THIS IS A TEST"
            pr_reviewer: "AlexAntn,vtikha,ilaria-carlini"
            pr_assignee: "AlexAntn"
            source_branch: "user_changes_19072021104501_test"
            github_token: ${{ secrets.GITHUB_TOKEN }}