# this workflow will generate the containers on push.

name: GZ_onCodeRelease

on: 
    repository_dispatch:
        types: [GZ_onCodeRelease]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}

            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


######## Command to build the full Docker image #########
            - name: Build gazebo Docker full image
              run: docker build ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.gazebo_unst_src }}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push gazebo Docker full image
              run: docker push ${{ github.event.client_payload.gazebo_unst_src }}
#########################################################################################

######## Command to build the thin Docker image #########
            - name: Build gazebo Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.unst_base_image_for_GZ_src }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4production --tag ${{ github.event.client_payload.gazebo_unst_bin }}
#########################################################################################

######### Command to push the thin Docker Image online ##################################
            - name: Push superbuild Docker thin image
              run: docker push ${{ github.event.client_payload.gazebo_unst_bin }}
#########################################################################################
