# this workflow will generate the containers of gazebo on push. 

name: GZ_onCodeChanges

on: 
    repository_dispatch:
        types: [GZ_onCodeChanges]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: icub-tech-iit/code
                  token: ${{ secrets.CODE_REPO_ACCSS_TOKEN }}
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

########### This command sets the master/release variable ##############################
            - name: set release/devel argument for Docker build
              run: |
                echo ${{ github.event.client_payload.version }} > RELEASE_TAG
                echo "release=$(cat RELEASE_TAG)" > RELEASE_ARG
                echo $(cat RELEASE_ARG)
#########################################################################################

######## Command to build the full Docker image, using only unstable tag #########
            - name: Build gazebo Docker full image
              run: docker build ${{ github.event.client_payload.docker_path }} --build-arg $(cat RELEASE_ARG) --file ${{ github.event.client_payload.docker_path }}/Dockerfile --tag ${{ github.event.client_payload.gazebo_unst_src}}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push gazebo Docker full image
              run: docker push ${{ github.event.client_payload.gazebo_unst_src }}
#########################################################################################

######## Command to build the thin Docker image, using only unstable tag #########
            - name: Build gazebo Docker thin image
              run: docker build --build-arg ${{ github.event.client_payload.unst_base_image_for_GZ_bin }} --build-arg ${{ github.event.client_payload.unst_base_image_for_GZ_src }} ${{ github.event.client_payload.docker_path }} --file ${{ github.event.client_payload.docker_path }}/Dockerfile4production --tag ${{ github.event.client_payload.gazebo_unst_bin }}
#########################################################################################

######### Command to push the full Docker Image online ##################################
            - name: Push gazebo Docker thin image
              run: docker push ${{ github.event.client_payload.gazebo_unst_bin}}
#########################################################################################
