name: Updating pr body

on: 
  repository_dispatch:
    types: [sending_test_outcome]

jobs:
  updating_pr_body:
    runs-on: [ubuntu-latest]
    steps:
    - name: Formatting test-script outcome
      id: format-outcome
      run: |
        test_outcome=$(echo ${{ github.event.client_payload.test_success }} | tr ' ' '\n')
        echo "Test outcome: $test_outcome"
        echo "::set-output name=test_outcome::$test_outcome"
        
    - uses: lauracavaliere/pr-update-action@master
      with:
        pr-context: "${{ toJson(github.event.client_payload.pr_context) }}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: 'add_app_\d+'
        body-template: |
              Test script result\:
              "${{ steps.format-outcome.outputs.test_outcome }}"
