name: Updating pr body

on: 
  repository_dispatch:
    types: [sending_test_outcome]

jobs:
  updating_pr_body:
    runs-on: [ubuntu-latest]
    steps:
    - name: Formatting test-script outcome
      id: format-outcome
      run: |
        test_outcome="${{ github.event.client_payload.test_success }}"
        test_outcome_list=($test_outcome)
        multilines_list="<ul>"
        for el in ${test_outcome_list[@]}
        do
          echo $el
          el=$(echo $el | tr ':' ': ')
          echo $el
          multilines_list="$multilines_list <li>$el</li>"
        done
        multilines_list="$multilines_list</ul>"
        echo "Result: $multilines_list"
        echo "::set-output name=test_outcome::$multilines_list"
        
    - uses: lauracavaliere/pr-update-action@master
      with:
        pr-context: "${{ toJson(github.event.client_payload.pr_context) }}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: 'add_app_\d+'
        body-template: |
              Test script result\:
              ${{ steps.format-outcome.outputs.test_outcome }}
